name: Build and Deploy Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: clone
      run: |
        git clone https://github.com/hanlee55/kakao-chatbot.git kakaochatbot

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Display directory structure
      run: |
        pwd
        echo "Directory structure of /home/runner/work/kakao-chatbot-docs/kakao-chatbot-docs/"
        tree .
        ls
        pwd
        echo "ls /home/runner/work/"
        ls /home/runner/work

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Sphinx documentation
      run: |
        sphinx-build -b html docs/ _sites
        tree .

    - name: Upload artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_sites

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
      pages: write

    
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
